name: Main

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        node_version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v5
      - uses: aboutbits/github-actions-node/setup-and-install@v3
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://npm.pkg.github.com'
          registry-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Lint
        run: npm run lint
        shell: bash
      - name: Typecheck
        run: npm run typecheck
        shell: bash

  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        node_version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v5
      - uses: aboutbits/github-actions-node/setup-and-install@v3
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://npm.pkg.github.com'
          registry-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Test
        run: npm run test
        shell: bash
